# 表情包API服务全局配置
emoji:
  check_interval: 5 # 扫描间隔（分钟）
  max_reg_num: 500 # 最大注册表情包数量
  do_replace: false # 达到最大数量后是否替换
  similarity_limit: 0.3 # 相似度限制
  # 可扩展更多emoji相关配置
model:
  vlm: "deepseek-ai/deepseek-vl2" # VLM模型名称
  utils: "Qwen/Qwen2-VL-72B-Instruct" # 通用模型名称
  base_url: "your-api-base-url" # API基础URL
  api_key: "your-api-key" # API密钥
  max_token: 2048 # 模型最大输出长度
  # 可扩展更多模型相关配置
# 机器人相关配置
bot:
  nickname: "AI表情助手" # 机器人昵称
# 可扩展更多全局配置
